# Generated by Django 2.2.10 on 2020-06-03 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0010_auto_20200508_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ga_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
